# Generated by Django 5.0.7 on 2024-07-28 22:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.CharField(editable=False, max_length=128, primary_key=True, serialize=False, unique=True)),
                ('display_name', models.CharField(max_length=128)),
                ('auth_user', models.CharField(max_length=128)),
                ('language', models.CharField(default='DE', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('discipline', models.CharField(choices=[('EIGHT_BALL', 'Eight Ball'), ('NINE_BALL', 'Nine Ball'), ('TEN_BALL', 'Ten Ball'), ('STRAIGHT_POOL', 'Straight Pool')], max_length=16)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('score_1', models.IntegerField()),
                ('score_2', models.IntegerField()),
                ('hidden', models.IntegerField()),
                ('rating_inflation', models.IntegerField(default=0)),
                ('comment', models.CharField(max_length=1024)),
                ('player_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player1', to='ranking.player')),
                ('player_2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player2', to='ranking.player')),
            ],
        ),
        migrations.CreateModel(
            name='AlternativePlayerName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_name', models.CharField(max_length=128)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranking.player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranking.player')),
            ],
        ),
    ]
