# Generated by Django 5.0.7 on 2024-07-28 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_id',
            field=models.CharField(max_length=128, primary_key=True, serialize=False, unique=True),
        ),
    ]
