# Generated by Django 5.0.7 on 2024-07-28 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0002_alter_player_player_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='player',
            name='auth_user',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
