# Generated by Django 5.0.7 on 2024-08-01 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0004_match_created_on_alter_match_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='context',
            field=models.CharField(default='test', max_length=128),
            preserve_default=False,
        ),
    ]
