# Generated by Django 5.0.7 on 2024-08-01 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0005_match_context'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=datetime.datetime.now)),
                ('period', models.CharField(choices=[('MONTH', 'Month'), ('ALL_TIME', 'All Time')], max_length=16)),
                ('rating_inflation', models.IntegerField()),
                ('start_rating', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='playerrating',
            name='period',
            field=models.CharField(choices=[('MONTH', 'Month'), ('ALL_TIME', 'All Time')], default='MONTH', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playerrating',
            name='rating',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='match',
            name='context',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='match',
            name='hidden',
            field=models.IntegerField(default=False),
        ),
    ]
