# Generated by Django 5.0.7 on 2024-08-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0006_settings_playerrating_period_playerrating_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='temperature',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
