# Generated by Django 5.0.7 on 2024-08-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0007_settings_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerrating',
            name='num_matches',
            field=models.IntegerField(default=0),
        ),
    ]
