# Generated by Django 5.0.7 on 2024-08-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0008_playerrating_num_matches'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerrating',
            name='discipline',
            field=models.CharField(choices=[('EIGHT_BALL', 'Eight Ball'), ('NINE_BALL', 'Nine Ball'), ('TEN_BALL', 'Ten Ball'), ('STRAIGHT_POOL', 'Straight Pool')], default='NINE_BALL', max_length=16),
            preserve_default=False,
        ),
    ]
