# Generated by Django 5.0.7 on 2024-08-04 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0009_playerrating_discipline'),
    ]

    operations = [
        migrations.CreateModel(
            name='LigaSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('discipline', models.CharField(choices=[('EIGHT_BALL', 'Eight Ball'), ('NINE_BALL', 'Nine Ball'), ('TEN_BALL', 'Ten Ball'), ('STRAIGHT_POOL', 'Straight Pool')], max_length=16)),
                ('race_to', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='playerrating',
            name='month',
            field=models.DateField(default=datetime.datetime(2024, 8, 4, 14, 47, 24, 799686)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='settings',
            name='rating_inflation',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='settings',
            name='start_rating',
            field=models.IntegerField(default=400),
        ),
        migrations.AlterField(
            model_name='settings',
            name='temperature',
            field=models.IntegerField(default=20),
        ),
    ]
