# Generated by Django 5.0.7 on 2024-08-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0010_ligasettings_playerrating_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerrating',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
